import lawyerImage from "../assets/images/lawyer1.png";

export const lawyerList = [
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
  {
    name: "유성열",
    name2: "(柳成烈)",
    img: lawyerImage,
    title: "변호사",
    phone: "02. 583. 6300",
    email: "ysl@lawvax.co.kr",
  },
];
